export const languages = [
  { code: 'en-US', name: 'English' },
  { code: 'hi-IN', name: 'Hindi' },
  { code: 'mr-IN', name: 'Marathi' },
  { code: 'bn-IN', name: 'Bengali' },
  { code: 'te-IN', name: 'Telugu' },
  { code: 'ta-IN', name: 'Tamil' },
  { code: 'kn-IN', name: 'Kannada' },
  { code: 'ml-IN', name: 'Malayalam' },
  { code: 'gu-IN', name: 'Gujarati' },
  { code: 'pa-IN', name: 'Punjabi' },
  { code: 'or-IN', name: 'Odia' },
  { code: 'as-IN', name: 'Assamese' },
  { code: 'ks-IN', name: 'Kashmiri' },
  { code: 'sd-IN', name: 'Sindhi' },
  { code: 'ur-IN', name: 'Urdu' },
  { code: 'sa-IN', name: 'Sanskrit' },
  { code: 'mai-IN', name: 'Maithili' },
  { code: 'brx-IN', name: 'Bodo' },
  { code: 'dog-IN', name: 'Dogri' },
  { code: 'kok-IN', name: 'Konkani' },
  { code: 'mni-IN', name: 'Manipuri' },
  { code: 'npi-IN', name: 'Nepali' },
  { code: 'sat-IN', name: 'Santali' },
  { code: 'snd-IN', name: 'Sindhi' }
];